package hs.database.annotations;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.FIELD)
public @interface Id {

  /**
   * Indicates whether the field is automatically generated by the underlying database or not.<p>
   *
   * If generated then for inserts the field must be <code>null</code>, otherwise it must not be
   * be <code>null</code>.
   *
   * @return whether or not the field is generated automatically
   */
  boolean generated() default true;
}
