//module hs.mediasystem.runner {
//  requires javafx.controls;
//  requires hs.mediasystem.util;
//  requires javax.inject;
//  requires reactfx;
//  requires mediasystem.ext.basic.media.types;
//  requires ddif.core;
//  requires mediasystem.domain;
//  requires java.desktop;
//  requires java.sql;
//  requires database.core;
//  requires com.fasterxml.jackson.databind;
//  requires com.fasterxml.jackson.core;
//  requires mediasystem.db;
//  requires ddif.plugins;
//  requires jlessc;
//  requires java.annotation;
//  requires hs.mediasystem.mediamanager;
//  requires hs.mediasystem.scanner;
//  requires jackson.annotations;
//  requires com.fasterxml.jackson.module.paramnames;
//  requires com.fasterxml.jackson.dataformat.yaml;
//  requires javafx.swing;
//  requires javafx.graphics;
//  requires com.sun.jna;
//  requires com.sun.jna.platform;
//}
